name: Publish Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build all packages
        run: bun run build

      - name: Publish changed packages
        # By setting the NPM_TOKEN env var, `bun publish` will automatically use it for authentication.
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          for pkg in packages/*; do
            if [ -d "$pkg" ]; then
              echo "INFO: Attempting to publish package in '$pkg'"
              (cd "$pkg" && bun publish --no-git-checks)
            fi
          done